# Generated by Django 4.2 on 2024-01-25 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('Introductory Email', 'Introductory Email'), ('Product Announcement', 'Product Announcement'), ('Cold Email', 'Cold Email'), ('Follow up', 'Follow up'), ('Survey Request', 'Survey Request'), ('Special Offer', 'Special Offer')], max_length=255)),
                ('email_subject', models.CharField(max_length=255)),
                ('email_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('Introductory Email', 'Introductory Email'), ('Product Announcement', 'Product Announcement'), ('Cold Email', 'Cold Email'), ('Follow up', 'Follow up'), ('Survey Request', 'Survey Request'), ('Special Offer', 'Special Offer')], max_length=255)),
                ('email_subject', models.CharField(max_length=255)),
                ('email_body', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('sent_to_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_email', to='accounts.lead')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_management.emailtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_template', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_management.emailtemplate')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.lead')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
